OPTIMIZER:
  NAME: 'Adam'
  PARAMS:
    lr: 1.0e-3
    weight_decay: 5.0e-4 
# SCHEDULER :
#   NAME: 'CyclicLR'
#   PARAMS : 
#     base_lr: 1e-4
#     max_lr : 
#     max_lr : 0.1
#     step_size_up : 2000
  
