defaults:
  - base_config
  - dataset: mnist_paddedto32
  - base_distribution: no_base_distribution
  - default_proposal: uniform
  - proposal: uniform
  - proposal_training : no_proposal_training
  - energy: conv_nijkamp_sn
  - ebm : ais
  - feature_extractor : null
  - explicit_bias : scalar_explicit_bias
  - train: self_normalized_short_term
  - regularization: no_reg
  - buffer: null
  - optim_f_theta: adamw
  - optim_proposal: adamw
  - optim_base_dist: adamw
  - optim_explicit_bias: adamw
  - scheduler_f_theta: null
  - scheduler_proposal: null
  - scheduler_base_dist: null
  - scheduler_explicit_bias: null
  - sampler_init_base_dist: nuts_mnist
  - sampler_init_buffer: nuts_mnist
  - sampler_init_data: nuts_mnist
  - sampler_init_proposal: nuts_mnist
  - machine: karolina

