defaults:
  - base_train_config_name
trainer_name: 'ais_self_normalized'
max_steps: null
max_epochs: 1000
output_folder: './Results'
load_from_checkpoint: false
seed: 42
just_test: false
decay_ema: null
task: 'distribution_estimation'
save_dir: null
multi_gpu: single
val_check_interval: null
save_energy_every: 100
samples_every: 1000
log_every_n_steps: 10
nb_steps_langevin : 10
step_size_langevin : 10.0
sigma_langevin : 1e-2
clip_max_norm : null
clip_max_value : 0.05
prop_replay_buffer: 1.0
size_buffer: 256
save_buffer_every: 1
clamp_min : 0.0
clamp_max : 1.0
batch_of_update: 128
store_on_gpu: True
