defaults:
  - base_config
  - dataset: mnist_paddedto32
  - base_distribution: proposal
  - default_proposal: gaussian # Only used when proposal is adaptive
  - proposal: real_nvp
  - proposal_training : log_prob_kl
  - energy: dc_gan_distribution
  - feature_extractor : null
  - explicit_bias : scalar_explicit_bias
  - train: self_normalized_distribution
  - optim_energy: adamw
  - optim_proposal: adamw
  - scheduler_energy: cyclic_lr
  - scheduler_proposal: cyclic_lr
  - sampler: nuts_mnist
  - machine: dtu_cluster

