defaults:
  - base_config
  - dataset: mnist_paddedto32
  - base_distribution: gaussian
  - default_proposal: gaussian # Only used when proposal is adaptive
  - proposal: vera
  - proposal_training : log_prob
  - energy: dc_gan_distribution
  - feature_extractor : null
  - explicit_bias : scalar_explicit_bias
  - train: vera_distribution
  - optim_energy: adamw
  - optim_proposal: adamw
  - sampler: nuts

