defaults:
  - base_config
  - dataset: checkerboard
  - base_distribution: no_base_distribution
  - default_proposal: gaussian
  - proposal: gaussian
  - proposal_training : no_proposal_training
  - energy: fc_distribution
  - feature_extractor : null
  - explicit_bias : scalar_explicit_bias
  - train: self_normalized_distribution
  - optim_f_theta: adamw
  - optim_proposal: adamw
  - optim_base_dist: adamw
  - optim_log_bias: adamw
  - scheduler_f_theta: null
  - scheduler_proposal: null
  - scheduler_base_dist: null
  - scheduler_log_bias: null
  - sampler: nuts
  - machine: dtu_cluster

