defaults:
  - base_config
  - dataset: mnist_paddedto32
  - base_distribution: no_base_distribution
  - default_proposal: gaussian # Only used when proposal is adaptive
  - proposal: real_nvp
  - proposal_training : log_prob
  - energy: dc_gan_distribution
  - feature_extractor : null
  - explicit_bias : scalar_explicit_bias
  - train: just_proposal_distribution
  - optim_energy: adamw
  - optim_proposal: adamw
  - sampler: nuts_mnist
  - machine: dtu_cluster

