defaults:
  - base_config
  - dataset: gas_maf
  - base_distribution: proposal
  - default_proposal: gaussian
  - proposal: gaussian_full
  - proposal_training : no_proposal_training
  - energy: fc_distribution_sn
  - feature_extractor : null
  - explicit_bias : scalar_explicit_bias
  - train: self_normalized_distribution
  - optim_energy: adamw
  - optim_proposal: adamw
  - optim_base_dist: adamw
  - scheduler_energy: cyclic_lr
  - scheduler_proposal: cyclic_lr
  - scheduler_base_dist: cyclic_lr
  - sampler: null
  - machine: dtu_cluster

