defaults:
  - base_config
  - dataset: checkerboard
  - base_distribution: no_base_distribution
  - proposal: gaussian
  - proposal_training : no_proposal_training
  - energy: fc_regression
  - feature_extractor : null
  - explicit_bias : no_explicit_bias
  - train: self_normalized_distribution
  - optim: adamw
  - sampler: null

