defaults:
  - base_config
  - dataset: mnist
  - base_distribution: proposal
  - proposal: gaussian
  - proposal_training : no_proposal_training
  - energy: conv_distribution
  - feature_extractor : null
  - explicit_bias : no_explicit_bias
  - train: self_normalized_distribution
  - optim: adamw
  - sampler: null

