defaults:
  - base_config
  - dataset: checkerboard
  - base_distribution: proposal
  - default_proposal: gaussian_larger
  - proposal: gaussian_larger
  - proposal_training : log_prob
  - energy: fc_distribution
  - feature_extractor : null
  - explicit_bias : scalar_explicit_bias
  - train: self_normalized_distribution
  - optim_energy: adamw
  - optim_proposal: adamw
  - scheduler_energy: cyclic_lr
  - scheduler_proposal: cyclic_lr
  - sampler: nuts
  - machine: dtu_cluster

