defaults:
  - base_config
  - dataset: mnist
  - base_distribution: proposal
  - default_proposal: gaussian # Only used when proposal is adaptive
  - proposal: real_nvp
  - proposal_training : log_prob_kl
  - energy: conv_distribution
  - feature_extractor : null
  - explicit_bias : scalar_explicit_bias
  - train: self_normalized_distribution
  - optim: adamw
  - sampler: nuts

