defaults:
  - base_config
  - dataset: mnist_paddedto32
  - base_distribution: gaussian_larger
  - default_proposal: gaussian_larger # Only used when proposal is adaptive
  - proposal: gaussian_mixture
  - proposal_training : log_prob_kl
  - energy: dc_gan_distribution
  - feature_extractor : null
  - explicit_bias : scalar_explicit_bias
  - train: self_normalized_distribution
  - optim_energy: adamw
  - optim_proposal: adamw
  - sampler: nuts_mnist
  - machine: dtu_cluster

