defaults:
  - base_config
  - dataset: checkerboard
  - base_distribution: gaussian_larger
  - default_proposal: gaussian # Only used when proposal is adaptive
  - proposal: vera_small
  - proposal_training : log_prob
  - energy: fc_distribution
  - feature_extractor : null
  - explicit_bias : scalar_explicit_bias
  - train: vera_distribution
  - optim_energy: adamw
  - optim_proposal: adamw
  - sampler: nuts
  - machine : dtu_cluster

