defaults:
  - base_config
  - dataset: 1d_regression_1
  - base_distribution: proposal
  - proposal: gaussian
  - proposal_training : no_proposal_training
  - energy: fc_regression
  - feature_extractor : toy_feature_extractor
  - explicit_bias : 1_layer_fc
  - train: self_normalized_regression
  - optim_energy: adamw
  - optim_proposal: adamw
  - sampler: nuts

