defaults:
  - base_config
  - dataset: checkerboard
  - base_distribution: gaussian
  - default_proposal: gaussian_more_noise
  - proposal: adaptive_mixture
  - proposal_training : no_proposal_training
  - energy: fc_regression
  - feature_extractor : null
  - explicit_bias : scalar_explicit_bias
  - train: self_normalized_distribution
  - optim_energy: adamw
  - optim_proposal: adamw
  - sampler: nuts
  - machine: dtu_cluster

