defaults:
  - base_config
  - dataset: mnist_paddedto32
  - base_distribution: proposal
  - default_proposal: gaussian_larger # Only used when proposal is adaptive
  - proposal: ppca
  - proposal_training : no_proposal_training
  - energy: dc_gan_distribution_sn
  - feature_extractor : null
  - explicit_bias : scalar_explicit_bias
  - train: self_normalized_distribution
  - optim_f_theta: adamw
  - optim_proposal: adamw
  - optim_base_dist: adamw
  - optim_log_bias: adamw
  - scheduler_f_theta: null
  - scheduler_proposal: null
  - scheduler_base_dist: null
  - scheduler_log_bias: null
  - sampler: nuts_mnist
  - machine: dtu_cluster

