defaults:
  - base_config
  - dataset: mnist_paddedto32
  - buffer: buffer_mnist
  - base_distribution: proposal
  - default_proposal: gaussian_larger # Only used when proposal is adaptive
  - proposal: ppca
  - proposal_training : log_prob
  - energy: dc_gan_distribution_sn
  - feature_extractor : null
  - explicit_bias : scalar_explicit_bias
  - train: just_proposal_distribution
  - regularization: l2_reg
  - optim_f_theta: adamw
  - optim_proposal: adamw
  - optim_base_dist: adamw
  - optim_explicit_bias: adamw
  - scheduler_f_theta: null
  - scheduler_proposal: null
  - scheduler_base_dist: null
  - scheduler_explicit_bias: null
  - sampler_init_base_dist: langevin
  - sampler_init_buffer: langevin
  - sampler_init_data: langevin
  - sampler_init_proposal: langevin
  - machine: dtu_cluster

