defaults:
  - base_config
  - dataset: mnist_paddedto32
  - buffer: buffer_mnist_padded32
  - base_distribution: no_base_distribution
  - default_proposal: gaussian_larger # Only used when proposal is adaptive
  - proposal: uniform
  - proposal_training : no_proposal_training
  - energy: dc_gan_distribution_sn
  - feature_extractor : null
  - explicit_bias : scalar_explicit_bias
  - train: persistent_replay_langevin_distribution
  - regularization: l2_reg
  - optim_f_theta: adamw
  - optim_proposal: adamw
  - optim_base_dist: adamw
  - optim_explicit_bias: adamw
  - scheduler_f_theta: null
  - scheduler_proposal: null
  - scheduler_base_dist: null
  - scheduler_explicit_bias: null
  - sampler: langevin_replay
  - machine: dtu_cluster

