defaults:
  - base_config
  - dataset: mnist_paddedto32
  - buffer: buffer_mnist
  - base_distribution: proposal
  - default_proposal: gaussian # Only used when proposal is adaptive
  - proposal: real_nvp
  - proposal_training : log_prob
  - energy: dc_gan_distribution_sn
  - feature_extractor : null
  - explicit_bias : scalar_explicit_bias
  - train: self_normalized_distribution
  - regularization: l2_reg
  - optim_energy: adamw
  - optim_proposal: adamw
  - optim_base_dist: adamw
  - optim_explicit_bias: adamw
  - scheduler_energy: cyclic_lr
  - scheduler_proposal: cyclic_lr
  - scheduler_base_dist: cyclic_lr
  - scheduler_explicit_bias: cyclic_lr
  - sampler_init_base_dist: langevin
  - sampler_init_buffer: langevin
  - sampler_init_data: langevin
  - sampler_init_proposal: langevin
  - machine: dtu_cluster

