from .MDNProposal import MDNProposalRegression, get_MDNProposalRegression
from .gaussian import GaussianRegression, get_GaussianRegression
from .uniform import UniformRegression, get_UniformRegression